### ISSUE TITLE
Error: Cannot destructure property `edges` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by IgnisDa** [katyo/publish-crates#151]
First off, thanks for the package!

This action has worked fine for me in the past but it has not been able to publish during some recent runs. It gives the error specified above. Here is the action [log](https://github.com/IgnisDa/printr/runs/2387331681?check_suite_focus=true#step:4:10).

EDIT:
Okay the error was raised because I forgot to change the version in `Cargo.toml` and cargo was trying to publish a version that had already been published. The error was fixed.

It would be nice to have some useful error messages for this, right?

**Comment by katyo** [comment]
@IgnisDa Seems you remove log. Could you post backtrace?

**Comment by katyo** [comment]
@IgnisDa Seems I fixed this issue. The root of problem in checking repository consistency which fails for detached refs (as ex. for PRs). See README in particular `check-repo` option and NOTEs below.

**Comment by katyo** [comment]
Closed as fixed.
Feel free reopen this issue.
