### ISSUE TITLE
Can't publish packages in workspace

### ISSUE THREAD

**Issue by wangfenjin** [katyo/publish-crates#291]
In the code I update both  libduckdb-sys and duckdb, but the published version can't be find

https://github.com/wangfenjin/duckdb-rs/runs/3512742679?check_suite_focus=true

```
Searching cargo packages at './'
Found packages: duckdb, libduckdb-sys
Checking packages consistency
Sorting packages according dependencies
Publishing package 'libduckdb-sys'
/usr/share/rust/.cargo/bin/cargo publish --no-verify --allow-dirty --all-features
    Updating crates.io index
   Packaging libduckdb-sys v0.2.3 (/home/runner/work/duckdb-rs/duckdb-rs/libduckdb-sys)
   Uploading libduckdb-sys v0.2.3 (/home/runner/work/duckdb-rs/duckdb-rs/libduckdb-sys)
/usr/share/rust/.cargo/bin/cargo update
    Updating crates.io index
Package 'libduckdb-sys' published successfully
Publishing package 'duckdb'
/usr/share/rust/.cargo/bin/cargo publish --no-verify --allow-dirty --all-features
    Updating crates.io index
   Packaging duckdb v0.2.3 (/home/runner/work/duckdb-rs/duckdb-rs)
error: failed to prepare local package for uploading

Caused by:
  failed to select a version for the requirement `libduckdb-sys = "^0.2.3"`
  candidate versions found which didn't match: 0.2.2, 0.2.1, 0.2.0, ...
  location searched: crates.io index
  required by package `duckdb v0.2.3 (/home/runner/work/duckdb-rs/duckdb-rs)`
Error: The process '/usr/share/rust/.cargo/bin/cargo' failed with exit code 101
```

**Comment by wangfenjin** [comment]
https://github.com/wangfenjin/duckdb-rs/pull/21/files this is my code change

**Comment by katyo** [comment]
@wangfenjin Sounds strange because this action awaits when published package will be available on registry and also triggers `cargo update` after publishing:
https://github.com/katyo/publish-crates/blob/a8c8cba58a52eefbcefdc3274d489442c9985129/src/main.ts#L59-L60

**Comment by wangfenjin** [comment]
yes, but acctually I had tried two times, still not succeed so I create this issue.

LOL, is it because the cargo crate server cache inconsistent?

**Comment by wangfenjin** [comment]
@katyo maybe after cargo update, we can ` await awaitCrateVersion(package_name, package_info.version) ` again, maybe will make things better...

**Comment by wangfenjin** [comment]
In order to test this, I always need to bump the version because after the first crate published, I can't publish the version again. 

So I'm thinking should we add settings to check if this version is already published and we can skip it, that way we don't need to bump the version every time...

**Comment by wangfenjin** [comment]
Another benefit is it also enable us only update one of the packages in the workspace

**Comment by katyo** [comment]
> In order to test this, I always need to bump the version because after the first crate published, I can't publish the version again.
> 
> So I'm thinking should we add settings to check if this version is already published and we can skip it, that way we don't need to bump the version every time...

> Another benefit is it also enable us only update one of the packages in the workspace

Such behavior already implemented by default (see description in README.md).
This action publishes only packages with updated versions which does not published yet skipping already published.

**Comment by katyo** [comment]
@wangfenjin Seems this problem related to cargo cache.
I think we may try repeat `cargo update` > `cargo publish` when publishing failed.

**Comment by wangfenjin** [comment]
https://github.com/wangfenjin/duckdb-rs/runs/3514142038?check_suite_focus=true

are you sure it’s the case? I rerun the workflow but still failed

**Comment by katyo** [comment]
Hmm, seems other error occurred.

**Comment by katyo** [comment]
@wangfenjin Could you test branch `fix-151`?

**Comment by alepez** [comment]
Hi. Thanks for your work. I just tried to use this action on a workspace, but it seems to fail to select the correct version.

Here we see "Package 'provola-terminalreporter' published successfully" but after that, the next crate which depends on it fails.

```
   Compiling strum_macros v0.23.1
   Compiling thiserror v1.0.30
   Compiling chrono v0.4.19
   Compiling provola-core v0.2.0
   Compiling provola-terminalreporter v0.2.0 (/home/runner/work/provola/provola/target/package/provola-terminalreporter-0.2.0)
    Finished dev [unoptimized + debuginfo] target(s) in 31.57s
   Uploading provola-terminalreporter v0.2.0 (/home/runner/work/provola/provola/provola-terminalreporter)
/home/runner/.cargo/bin/cargo update
    Updating crates.io index
Package 'provola-terminalreporter' published successfully
Publishing package 'provola-reporters'
/home/runner/.cargo/bin/cargo publish
    Updating crates.io index
   Packaging provola-reporters v0.2.0 (/home/runner/work/provola/provola/provola-reporters)
   Verifying provola-reporters v0.2.0 (/home/runner/work/provola/provola/provola-reporters)
error: failed to verify package tarball

Caused by:
  failed to select a version for the requirement `provola-terminalreporter = "^0.2.0"`
  candidate versions found which didn't match: 0.1.7
  location searched: crates.io index
  required by package `provola-reporters v0.2.0 (/home/runner/work/provola/provola/target/package/provola-reporters-0.2.0)`
```

**Comment by alexxbb** [comment]
Got the same error:

`Error: Unable to determine latest modification time for local package 'hapi-rs' due to: 'TypeError: Cannot destructure property 'edges' of 'result.repository.ref.target.history' as it is undefined.'`

@katyo Do you happen to know what caused this?

**Comment by wangfenjin** [comment]
Anyone have this issue can also try my fork

**Comment by wangfenjin** [comment]
Example https://github.com/wangfenjin/duckdb-rs/blob/main/.github/workflows/release.yaml

**Comment by alexxbb** [comment]
Update: The error seems related to the crate's version in my case. I forgot to update the Cargo.toml and got this error. Once I updated the version the Action started working again.
