### ISSUE TITLE
Wrong dependency order is being generated

### ISSUE THREAD

**Issue by jmgilman** [katyo/publish-crates#305]
See an example run here: https://github.com/jmgilman/vaultrs/runs/3570403636?check_suite_focus=true

The correct order should be: `vaultrs-test` -> `vaultrs` -> `vaultrs-login`. This can be reasoned as follows:

* `vaultrs-test` has no internal dependencies
* `vaultrs` and `vaultrs-login` both have dev dependencies on `vaultrs-test`
* `vaultrs-login` has a direct dependency on `vaultrs`

In the example linked above, it attempted to publish `vaultrs` first which failed because the required `vaultrs-test` version doesn't yet exist in the crates.io registry.

Perhaps this dependency graph is too complex, in which case, an optional override parameter should be added so we can manually specify the correct order.

**Comment by katyo** [comment]
@jmgilman Thanks for issue.

Currently this action does not process `dev-dependencies`.
I planned to solve this later because I too busy just now.
Could you fix this? PRs are welcome.

**Comment by jmgilman** [comment]
I took a gander at the code and without being too familiar with Typescript I'm afraid I'm not going to be of much help at the moment. I'll try and revisit it soon but unfortunately it'll end up taking me a bit to come up to speed.
