### ISSUE TITLE
Support wildcards in workspace.members

### ISSUE THREAD

**Issue by dnbln** [katyo/publish-crates#314]
I have a `Cargo.toml` at the root of my workspace, which looks like this:

```toml
[workspace]
members = ["crates/*"]
```

<details>
<summary>Output</summary>
<pre>
Run katyo/publish-crates@v1
Searching cargo packages at '.'
Error: Manifest file 'crates/*/Cargo.toml' not found (ENOENT: no such file or directory, stat 'crates/*/Cargo.toml')
</pre>
</details>

(Run: https://github.com/dblanovschi/robespierre/runs/3641460175)

This seems to be the relevant code:

https://github.com/katyo/publish-crates/blob/5cb50445e250bfeb7f823f4785be2de044f4ba7a/src/package.ts#L130-L136

**Comment by katyo** [comment]
@dnbln For now this should be supported. Could you help with testing?

**Comment by katyo** [comment]
Closed as fixed. Feel free reopen this issue.
