### ISSUE TITLE
Support caret and implicit caret in dependency version

### ISSUE THREAD

**Issue by adlerjohn** [katyo/publish-crates#365]
The dependency version check checks for an _exact_ match.

https://github.com/katyo/publish-crates/blob/b9f892948cc44179a7d686293d2277fa2e958f15/src/package.ts#L194

It should instead allow for implicit and explicit caret versions, which crates.io supports.

**Comment by adlerjohn** [comment]
Potentially duplicate of #78

**Comment by katyo** [comment]
Semver match is unsafe for internal dependencies for some reasons.

**Comment by katyo** [comment]
@adlerjohn For now semver is used for check. Could you test it?

**Comment by adlerjohn** [comment]
Yes, it works now. Thank you!
