### ISSUE TITLE
Add argument for timeout/retry

### ISSUE THREAD

**Issue by adlerjohn** [katyo/publish-crates#366]
crates.io is not consistent (in a distributed systems sense). To account for this, should add an argument to configure some timeout where the action simply sleeps after successfully querying crates.io for a published workspace crate, and before actually attempting to publish the next one.

Potentially a retry feature can also be added, to try crates.io several times before finally aborting.

**Comment by katyo** [comment]
@adlerjohn Fixed, testing needed

**Comment by adlerjohn** [comment]
Nice. Only you publish a new version to the marketplace I'll update our pipelines and test it out!

**Comment by katyo** [comment]
@adlerjohn I updated v1 just now.

**Comment by adlerjohn** [comment]
Ref: https://github.com/katyo/publish-crates/pull/379

**Comment by adlerjohn** [comment]
Confirmed the delay works. Thanks!
