### ISSUE TITLE
Cannot read properties of undefined (reading 'path')

### ISSUE THREAD

**Issue by daniestevez** [katyo/publish-crates#648]
I'm trying to use publish-crates on the following crate: https://github.com/maia-sdr/maia-sdr/tree/main/maia-httpd

I'm getting the following error:
```
Found packages: maia-httpd
Checking packages consistency
Error: TypeError: Cannot read properties of undefined (reading 'path')
```
([full action run](https://github.com/maia-sdr/maia-sdr/actions/runs/4640315900/jobs/8212421029)).

I'm calling publish-crates from [this reusable workflow](https://github.com/maia-sdr/maia-sdr/blob/main/.github/workflows/publish.yml), which gets [run from this workflow](https://github.com/maia-sdr/maia-sdr/blob/main/.github/workflows/maia-httpd.yml#L56).

I'm also finding the same problem in [another crate in the same repo](https://github.com/maia-sdr/maia-sdr/actions/runs/4640319873/jobs/8212184828). The thing these two crates have in common is that they have some dependencies with `path` and `version`. Another simpler crate in the same repo works fine with publish-crates.

**Comment by katyo** [comment]
@daniestevez Seems need add packages (maia-json, maia-pac) to workspace members.

**Comment by daniestevez** [comment]
I'm not using a workspace. Do I need to use a workspace for this action to work?

**Comment by katyo** [comment]
Seems this issue is solved in main branch.
Feel free reopen it otherwise.
