### ISSUE TITLE
Output: list of published crates

### ISSUE THREAD

**Issue by boozook** [katyo/publish-crates#664]
Please add outputs to action: 
- list of published crates with versions
- list of not published crates with versions

It could be very useful for making release notes for workspaces.
Thanks! ❤️

**Comment by katyo** [comment]
@boozook 
I have no free time to work with it right now. But I still review and accept pull-requests (may be delayed) if you would like to do it yourself.

**Comment by boozook** [comment]
That's ok, same for me.

**Comment by boozook** [comment]
Okay, I did it somehow 🤪
