### ISSUE TITLE
Add option `unmodified-only` to publish only "hasn't modified since the version change"-crates

### ISSUE THREAD

**Issue by boozook** [katyo/publish-crates#665]
Not all devs have ideal workflow/pipeline where they can publish entire workspace in one time and all crates bumped just just moment ago.
I suppose this option would be useful for cases where development over crates going in parallel (or concurrent?).

```
It seems package 'foo' modified since '0.1.0' so new version should be published
```

Seems #662 is related issue.

**Comment by katyo** [comment]
@boozook To prevent publishing specific crate you can simply leave the version unchanged. Only new (changed) versions will be published.

**Comment by boozook** [comment]
I tried it with `check-repo` and get failure with mentioned error `It seems package 'foo' modified since '0.1.0' so new version should be published`. Perhaps I don't understand how it works... 🤔

**Comment by katyo** [comment]
@boozook Have you tried `ignore-unpublished-changes`?
Setting `check-repo` to `false` also helps ignoring local changes when version does not bumped.

**Comment by boozook** [comment]
It works 👍
Thank you.
