### ISSUE TITLE
Error: TypeError: Cannot read properties of undefined (reading 'path')

### ISSUE THREAD

**Issue by kolbma** [katyo/publish-crates#677]
I've just wanted to publish a new version of my crate with github workflow and it doesn't work any longer...

Always see now the error `Error: TypeError: Cannot read properties of undefined (reading 'path')`

```
##[debug]Evaluating condition for step: 'Run katyo/publish-crates@v2'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Run katyo/publish-crates@v2
##[debug]Loading inputs
##[debug]Evaluating: secrets.[...]
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> '[...]'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating: github.token
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'token'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Loading env
Run katyo/publish-crates@v2
Searching cargo packages at '.'
/home/runner/.cargo/bin/cargo metadata --no-deps --format-version 1 --manifest-path Cargo.toml
{[...]
}
Found packages: [...]
Checking packages consistency
Error: TypeError: Cannot read properties of undefined (reading 'path')
##[debug]Node Action run completed with exit code 1
##[debug]Set output published = []
##[debug]Finishing: Run katyo/publish-crates@v2
```

**Comment by kayagokalp** [comment]
We are having the same problem -> https://github.com/FuelLabs/sway/actions/runs/7564155660/job/20598539836

For some reason I have a feeling that this is somehow related to bumping to rust 1.75 as our repos that use 1.74 had successful release runs with this crate.

**Comment by kolbma** [comment]
It has to do with this commit: https://github.com/katyo/publish-crates/commit/2975306b7d9a99df113de64c106802fb5088be56#diff-20da981bb437131fc964cf3ac8dbda479f1ef5a050f6e750dd518f8a3c533663L120-L128

I've a dev-dependency with path and no workspaces.  
The dev-dependency is not to publish.  
This has worked before, it has been ignored.  

Now here...
https://github.com/katyo/publish-crates/blob/31ec30415f7f62db3e7aea71dbc1c3995876cf40/src/package.ts#L223-L244

`dependency_package` line 227 is undefined.  
It pushes an error.  
Then later at line 238 it wants to compare `dependency_package.path` of undefined.
There is missing a `continue` or `break` after the error push at line 233.

Then I would see in the action output:  
`Error: Package 'xxx' dependes from internal 'yyy' which is not a workspace member. Listed workspace members only will be published`

And then there is some logic required to handle the dependencies correctly.
