### ISSUE TITLE
How to select only some crates from workspace?

### ISSUE THREAD

**Issue by s1341** [katyo/publish-crates#752]
I have a few crates in my workspace, including examples (specified as a wildcard `examples/*` in the `workspace.members` list). I don't want to publish the examples.

How can I select which crates to publish from the workspace?

**Comment by katyo** [comment]
You can simply add `publish = false` to examples. See https://doc.rust-lang.org/cargo/reference/manifest.html#the-publish-field

**Comment by s1341** [comment]
Thanks. Wasn't aware of that flag!
