### ISSUE TITLE
Semver compatible internal/path dependencies

### ISSUE THREAD

**Issue by simlay** [katyo/publish-crates#78]
I notice that there's a hard equality for [internal/path dependencies](https://github.com/katyo/publish-crates/blob/5cfa019eba211f5d3c50cbc747128658ab32ab21/src/package.ts#L195) when I think it should be based on [semver comparability](https://semver.org/spec/v1.0.0.html#spec-item-8). 

In my case, [`fluvio-auth` depends on a relative path and a version of `0.1.0` for `fluvio-dataplane-protocol`](https://github.com/infinyon/fluvio/blob/d4522dbba94512ff8b05cfa5205b80d26076e358/src/auth/Cargo.toml#L18) but [`fluvio-dataplane-protocol` has a version of `0.1.5`](https://github.com/infinyon/fluvio/blob/d4522dbba94512ff8b05cfa5205b80d26076e358/src/dataplane-protocol/Cargo.toml#L3). 

If I understand semver correctly, this should be okay no?

Anyway, if you're open to this feature I'm open to looking into adding it.

**Comment by katyo** [comment]
I think sevmer-based version matching is also acceptable for internal dependencies.
But we should be sure that current actual version of dependency published before publishing dependent package despite of already published semver-acceptable version.

**Comment by katyo** [comment]
@simlay Seems I fixed this issue. Could you help with testing?

**Comment by katyo** [comment]
Closed as fixed. Feel free reopen this issue.
